### PR TITLE
update SearchHelper.cs and format HandlesHelper.cs.

### PR DESCRIPTION
**Pull request by Donovoi**
Hi Carlos, i've finally had time to try this out. I believe I fix the long path issue. I have not cleaned the code (I would like to extract the classes and struct), before I take time to properly clean it. are you able to test and see if this is what you were after? 

Please also let me know if you prefer a different style or I should not be doing certain things. 

Thank you

### CODE REVIEW

**Comment by carlospolop** [comment]
hey @Donovoi,
I was checking the code (which looks nice, thanks for the PR), and noticed this: https://github.com/carlospolop/PEASS-ng/pull/325/commits/ae8ae94473efad5666ac60473ca3f42948cde374#diff-45fa516347fb9db93d7a468ffe13862dc609e257faf48c610cef00d6cca8fbaeR270

Does this mean that your code isn't still checking long path?

**Comment by carlospolop** [comment]
Hello?

**Comment by Donovoi** [comment]
Hi Carlos sorry about the late reply I'm on holiday atm, but happy to get this done. I've been doing some searching, and my plan is to create tests in `winPEAS.Tests` that verify the the `GetFiles()` method is bypassing the 260 char limit instead of just ignoring the files or skipping them. I've created a test but the `winPEAS.Helpers.Search.SearchHelper` is an internal class and not accessible from another assembly which is what winPEAS.Tests seems to be. So here is the test code (had to use fsutil because we are using such an older version of c#):  ```

        [TestMethod]
        public void TestGetFilesBypassesMAX_PATHLimit()
        {
            // Create a folder with files that have names longer than 260 characters
            string folder = "C:\\Temp\\TestFolder";
            for (int i = 0; i < 10; i++)
            {
                string longName = new string('a', 300);
                string fileName = Path.Combine(folder, $"{longName}_{i}.txt");

                // Use the fsutil command to create a file with a long name
                ProcessStartInfo startInfo = new ProcessStartInfo("fsutil", $"file createnew {fileName} 0")
                {
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                Process.Start(startInfo);
            }

            // Call the GetFilesWrapper method to get a list of all the files in the folder
            List<FileInfo> files = SearchHelper.GetFilesWrapper(folder);

            // Get a list of all the files in the folder using Directory.GetFiles
            string[] directoryFiles = Directory.GetFiles(folder);
            List<FileInfo> expectedFiles = directoryFiles.Select(f => new FileInfo(f)).ToList();

            // Make sure the lists have the same number of elements
            Assert.AreEqual(expectedFiles.Count, files.Count);

            // Make sure all of the elements in the list returned by GetFiles are also present in the list returned by Directory.GetFiles
            foreach (FileInfo file in files)
            {
                Assert.IsTrue(expectedFiles.Contains(file));

            }

        }
        
```

But `SearchHelper` is not accessible even if I create a public wrapper the for the private `GetFiles()` method. 


What do you suggest?

**Comment by carlospolop** [comment]
Hi @Donovoi,
Sorry man, I didn't see the last message.
I didn't create the winpeas tests so I'm not sure about how they work. Any new ideas from the time you wrote the message?

**Comment by Donovoi** [comment]
Hey sorry about the late reply. So apparently according to ChatGPT - The AlphaFS library should fix everything for us. It's like a better version of System.IO. Here is the info:

`https://alphafs.alphaleonis.com/`

and here is what you need to add in the usings: 

```
using DirectoryInfo = Alphaleonis.Win32.Filesystem.DirectoryInfo;
using FileInfo = Alphaleonis.Win32.Filesystem.FileInfo;
```

from my one test - everything else remains the same, but I think it needs more then one test. 
Once I'm confident it works, I'll let you know.

**Comment by carlospolop** [comment]
Hi @Donovoi, please check it and send a PR!

**Pull request closed without merging**
